# 官方文档：https://docs.docker.com/compose/compose-file/
version: "3.7"

services:
  redis:
    container_name: 'ginbase_redis'
    image: redis:6-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
      - ./config/redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf

  postgresql:
    container_name: "ginbase_postgresql"
    image: postgres:9.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  rabbitmq:
    container_name: "ginbase_rabbitmq"
    image: rabbitmq:3.8-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./data/rabbitmq/etc:/etc/rabbitmq
      - ./data/rabbitmq/data:/var/lib/rabbitmq

  app:
    container_name: ginbase_app
    build:
      context: .
      dockerfile: ./docker/base/Dockerfile
    depends_on:
      - rabbitmq
      - postgresql
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.yaml:/deploy/config/config.yaml
      - ./log:/deploy/log
    command: sh -c 'dockerize -wait tcp://postgresql:5432 && ./gin-base -c config/config.yaml'

  dbmigrate_app:
    container_name: ginbase_dbmigrate_app
    build:
      context: .
      dockerfile: ./docker/dbmigrate/Dockerfile
    environment:
      - RACK_ENV=development
    depends_on:
      - postgresql
    volumes:
      - ./config/database.yml:/deploy/config/database.yml
    command: sh -c 'dockerize -wait tcp://postgresql:5432 && rake db:migrate'
