redis:
  addr: 'localhost:6379'
  password: ''
  db: 0 # use default DB
  dial_timeout: 60   # 单位：秒
  read_timeout: 2   # 单位：秒
  write_timeout: 2  # 单位：秒
  pool_size: 60
pgsql:
  database: 'ginbase'
  username: 'zlei1'
  password: '123456'
  host: 'localhost'
  port: '5432'
