app:
  run_mode: debug
  port: 8080
  name: ginbase
  secret:
redis:
  addr: 'redis:6379'
  password: ''
  db: 0 # use default DB
  dial_timeout: 60   # 单位：秒
  read_timeout: 2   # 单位：秒
  write_timeout: 2  # 单位：秒
  pool_size: 60
pgsql:
  database: 'ginbase'
  username: 'postgres'
  password: ''
  host: 'postgresql'
  port: '5432'
