app:
  name: ginbase
  run_mode: debug
  port: '8080'
  host: ''
  secret: 6ba69021f60827a0a17203e50d2f189f530b54889bfab8c0e4f93bb18fa1f401
log:
  writers: file,stdout # 有2个可选项：file,stdout。选择file会将日志记录到file指定的日志文件中，选择stdout会将日志输出到标准输出，当然也可以两者同时选择
  level: DEBUG # 日志级别，DEBUG, INFO, WARN, ERROR, FATAL
  file: log/ginbase.log
  warn_file: log/ginbase.warn.log
  error_file: log/ginbase.error.log
  max_size: 500 # megabytes
  max_backups: 3
  max_age: 28 # days
redis:
  addr: 'redis:6379'
  password: ''
  db: 0 # use default DB
  dial_timeout: 60   # 单位：秒
  read_timeout: 2   # 单位：秒
  write_timeout: 2  # 单位：秒
  pool_size: 60
pgsql:
  host: 'postgresql'
  database: 'ginbase'
  username: 'postgres'
  password: ''
  port: '5432'
