info:
  contact: {}
  license: {}
paths:
  /api/admin/admins:
    get:
      parameters:
      - description: 页
        in: body
        name: page
        required: true
        schema:
          type: integer
      - description: 页数
        in: body
        name: per_page
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"message":"ok","data":{}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 查看管理员
      tags:
      - admin
    post:
      parameters:
      - description: 手机号
        in: body
        name: phone
        required: true
        schema:
          type: integer
      - description: 姓名
        in: body
        name: name
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"message":"ok","data":{}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 创建管理员
      tags:
      - admin
  /api/admin/admins/:id:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"message":"ok","data":{}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 删除管理员
      tags:
      - admin
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"message":"ok","data":{}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 查看管理员详情
      tags:
      - admin
    put:
      parameters:
      - description: 手机号
        in: body
        name: phone
        required: true
        schema:
          type: integer
      - description: 姓名
        in: body
        name: name
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"message":"ok","data":{}}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 修改管理员
      tags:
      - admin
  /api/admin/sessions:
    post:
      parameters:
      - description: 手机号
        in: body
        name: phone
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"message":"ok","data":{}}'
          schema:
            type: string
      summary: 管理员登入
      tags:
      - admin
  /api/client/sessions:
    post:
      parameters:
      - description: 手机号
        in: body
        name: phone
        required: true
        schema:
          type: string
      - description: 手机验证码
        in: body
        name: vcode
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"message":"ok","data":{}}'
          schema:
            type: string
      summary: 客户端用户登入
      tags:
      - client
  /api/common/captcha:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"message":"ok","data":{"captcha_token": "", "captcha": ""}}'
          schema:
            type: string
      summary: 获取图形验证码
      tags:
      - common
  /api/common/phone_verify_code:
    get:
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"message":"ok","data":{}}'
          schema:
            type: string
      summary: 获取手机验证码
      tags:
      - common
swagger: "2.0"
