info:
  contact: {}
  license: {}
paths:
  /api/client/sessions:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"message":"ok","data":{}}'
          schema:
            type: string
      summary: 用户登入
  /api/common/captcha:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"message":"ok","data":{"captcha_token": "", "captcha": ""}}'
          schema:
            type: string
      summary: 获取图形验证码
  /api/common/phone_verify_code:
    get:
      parameters:
      - description: 手机号
        in: body
        name: phone
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"message":"ok","data":{}}'
          schema:
            type: string
      summary: 获取手机验证码
swagger: "2.0"
