name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push ginbase Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: 18379183453/ginbase
          tags: latest
          dockerfile: ./docker/base/Dockerfile

      - name: Build and push ginbase-dbmigrate Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: 18379183453/ginbase-dbmigrate
          tags: latest
          dockerfile: ./docker/dbmigrate/Dockerfile
